# Generated by Django 2.1.8 on 2019-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_xes', '0002_auto_20190621_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='xes_file',
        ),
        migrations.AddField(
            model_name='processcube',
            name='case_level',
            field=models.BooleanField(default=False),
        ),
    ]
